In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\PRAVALLIKA\Downloads\playground-series-s6e7\train.csv")
df

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690083,690083,at-risk,6.31,69.7,24.11,2157.0,NaN,30.8,3.00,non-veg,high,poor,active,yes,female
690084,690084,at-risk,5.78,54.0,26.36,2858.0,6488.0,52.4,1.46,veg,medium,average,moderate,no,male
690085,690085,fit,7.64,85.7,21.91,2195.0,9241.0,41.3,1.57,non-veg,NaN,average,active,no,male
690086,690086,at-risk,6.74,73.0,18.73,2061.0,13366.0,56.6,2.60,balanced,NaN,average,active,yes,male
690087,690087,at-risk,5.55,69.3,24.38,2257.0,5144.0,47.9,1.76,balanced,medium,average,moderate,yes,male

In [3]:
df.shape

(690088, 15)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.skew(numeric_only=True)

id                    -9.610032e-17
sleep_duration        -8.232339e-03
heart_rate             4.382013e-04
bmi                    2.463976e-02
calorie_expenditure   -1.839400e-01
step_count            -1.802384e-01
exercise_duration     -3.746098e-01
water_intake           1.099603e-01
dtype: float64

In [6]:
df.describe()

,id,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake
count,690088.00000,614089.000000,682255.000000,676190.000000,637235.000000,676172.000000,683187.000000,646611.000000
mean,345043.50000,6.992597,75.096504,22.984925,2226.084931,8615.953050,38.751456,2.188542
std,199211.39062,1.215407,8.175106,2.481787,347.532098,3929.399831,14.742189,0.518489
min,0.00000,3.000000,50.000000,16.000000,1200.000000,1002.000000,0.000000,0.500000
25%,172521.75000,6.160000,69.400000,21.320000,2053.000000,5389.000000,29.200000,1.840000
50%,345043.50000,6.990000,75.100000,22.990000,2241.000000,8856.000000,39.400000,2.170000
75%,517565.25000,7.810000,80.700000,24.660000,2456.000000,12114.000000,49.400000,2.500000
max,690087.00000,10.000000,107.700000,34.820000,3580.000000,14999.000000,99.800000,4.720000

In [7]:
df.describe(include=["object"])

C:\Users\PRAVALLIKA\AppData\Local\Temp\ipykernel_9976\3753758486.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=["object"])

,health_condition,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
count,690088,683187,607277,631757,653467,661506,668715
unique,3,3,3,3,3,3,3
top,at-risk,veg,medium,average,moderate,yes,male
freq,592561,231432,261819,213948,221041,223730,237756

In [8]:
df.head()

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male

In [9]:
df.isnull().sum()

id                             0
health_condition               0
sleep_duration             75999
heart_rate                  7833
bmi                        13898
calorie_expenditure        52853
step_count                 13916
exercise_duration           6901
water_intake               43477
diet_type                   6901
stress_level               82811
sleep_quality              58331
physical_activity_level    36621
smoking_alcohol            28582
gender                     21373
dtype: int64

In [10]:
df.columns

Index(['id', 'health_condition', 'sleep_duration', 'heart_rate', 'bmi',
       'calorie_expenditure', 'step_count', 'exercise_duration',
       'water_intake', 'diet_type', 'stress_level', 'sleep_quality',
       'physical_activity_level', 'smoking_alcohol', 'gender'],
      dtype='str')

In [11]:
df["health_condition"].unique()

<StringArray>
['unhealthy', 'at-risk', 'fit']
Length: 3, dtype: str

# Feature Engineering

In [12]:
bmi_deviation = (np.maximum(0,18.5 - df["bmi"])+np.maximum(0,df["bmi"] - 24.9))

df["bmi_risk"] = np.clip(bmi_deviation / 10,0,1)

df["stress_risk"] = (df["stress_level"].map({"low": 0.0,"medium": 0.5,"high": 1.0}))

df["sleep_duration_risk"] = np.clip(abs(df["sleep_duration"] - 8) / 4,0,1)

step_risk = (1 -np.clip(df["step_count"] / 10000,0,1))

exercise_risk = (1 -np.clip(df["exercise_duration"] / 60,0,1))

calorie_risk = (1 -np.clip(df["calorie_expenditure"] / 600,0,1))

df["activity_risk"] = (0.40 * step_risk+0.30 * exercise_risk+0.30 * calorie_risk)

heart_rate = df["heart_rate"]

df["heart_rate_risk"] = np.clip(np.where(heart_rate < 60,(60 - heart_rate) / 20,np.where(heart_rate > 100,(heart_rate - 100) / 40,0)),0,1)

df["water_risk"] = (1 -np.clip(df["water_intake"] / 3,0,1))

df["sleep_quality_risk"] = (df["sleep_quality"].map({"poor": 1.0,"average": 0.5,"good": 0.0}))

df["lifestyle_risk"] = (df["smoking_alcohol"].map({"no": 0.0,"occasional": 0.5,"yes": 1.0}))

In [13]:

risk_columns = ["bmi_risk","stress_risk","sleep_duration_risk","activity_risk","heart_rate_risk","water_risk","sleep_quality_risk","lifestyle_risk"]

print("nan values in risk features:")

print(df[risk_columns].isnull().sum())

nan values in risk features:
bmi_risk               13898
stress_risk            82811
sleep_duration_risk    75999
activity_risk          71973
heart_rate_risk            0
water_risk             43477
sleep_quality_risk     58331
lifestyle_risk         28582
dtype: int64

In [14]:

df["health_risk_score"] = (100 *(0.20 * df["bmi_risk"]+0.15 * df["stress_risk"]+0.15 * df["sleep_duration_risk"]+0.20 * df["activity_risk"]+

    0.10 * df["heart_rate_risk"]+0.10 * df["water_risk"]+0.05 * df["sleep_quality_risk"]+0.05 * df["lifestyle_risk"]))

In [15]:
df = df.dropna(subset=["health_condition","health_risk_score"]).reset_index(drop=True)

In [16]:
df["health_risk_score"] = np.clip(df["health_risk_score"],0,100)

# splitting input and target features

In [17]:
X = df.drop(columns=["id","health_condition","health_risk_score"])
y_class = df["health_condition"]
y_reg = df["health_risk_score"]

In [18]:
X.shape

(390051, 21)

In [19]:
y_class.shape

(390051,)

In [20]:
y_class.value_counts()

health_condition
at-risk      334751
unhealthy     33021
fit           22279
Name: count, dtype: int64

In [21]:
y_reg.shape

(390051,)

# Train_Test_Split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(X,y_class,y_reg,test_size=0.20,random_state=23,stratify=y_class)

In [24]:
X_train.shape,X_test.shape,y_class_train.shape,y_class_test.shape,y_reg_train.shape, y_reg_test.shape

((312040, 21), (78011, 21), (312040,), (78011,), (312040,), (78011,))

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
label_encoder = LabelEncoder()
y_class_train_enc = (label_encoder.fit_transform(y_class_train))
y_class_test_enc = (label_encoder.transform(y_class_test))

In [27]:
label_encoder.classes_

array(['at-risk', 'fit', 'unhealthy'], dtype=object)

# splitting the data based on datatype for regression

In [28]:
num_cols = ["sleep_duration","heart_rate","bmi","calorie_expenditure","step_count","exercise_duration","water_intake","bmi_risk","stress_risk",
            "sleep_duration_risk","activity_risk","heart_rate_risk","water_risk","sleep_quality_risk","lifestyle_risk"]

In [29]:
nominal_cols = ["diet_type","smoking_alcohol","gender"]

In [30]:
ord_cols = ["stress_level","sleep_quality","physical_activity_level"]

In [31]:
ordinal_categories = [["low","medium","high"],["poor","average","good"],["sedentary","moderate","active"]]

# Data Preprocessing

In [32]:
from sklearn.impute import SimpleImputer

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [35]:
from sklearn.pipeline import Pipeline

In [36]:
from sklearn.compose import ColumnTransformer

In [37]:
num_pipeline = Pipeline([("imputer",SimpleImputer(strategy="median")),
                         ("scaler",StandardScaler())])

In [38]:
nominal_pipeline = Pipeline([("imputer",SimpleImputer(strategy="most_frequent")),
                             ("encoder",OneHotEncoder(handle_unknown="ignore",drop="first"))])

In [39]:
ordinal_pipeline = Pipeline([("imputer",SimpleImputer(strategy="most_frequent")),
                           ("encoder",OrdinalEncoder(categories=ordinal_categories))])

In [40]:
preprocessing = ColumnTransformer([("numerical",num_pipeline,num_cols),
                                   ("nominal",nominal_pipeline,nominal_cols),
                                   ("ordinal",ordinal_pipeline,ord_cols)])

In [41]:
X_train_p = (preprocessing.fit_transform(X_train))

X_test_p = (preprocessing.transform(X_test))

y_class_train_enc = np.asarray(y_class_train_enc, dtype="int32")

y_class_test_enc = np.asarray(y_class_test_enc,dtype="int32")

y_reg_train = np.asarray(y_reg_train,dtype="float32")

y_reg_test = np.asarray(y_reg_test,dtype="float32")

# Architecture Building

In [42]:
from keras.layers import Input,Dense,Dropout

from tensorflow.keras.models import Model

from tensorflow.keras.optimizers import Adam

from tensorflow.keras.callbacks import EarlyStopping

from sklearn.utils.class_weight import compute_class_weight

In [43]:
input_layer = Input(shape=(X_train_p.shape[1],))

h1 = Dense(96,activation="relu")(input_layer)
h1 = Dropout(0.30)(h1)

h2 = Dense(32,activation="relu")(h1)
h2 = Dropout(0.20)(h1)

o= Dense(16,activation="relu")(h2)


classification_output = Dense(3,activation="softmax",name="classification")(o)


regression_output = Dense(1,activation="linear",name="regression")(o)


modelf = Model(inputs=input_layer,outputs=[classification_output,regression_output])
modelf.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 24)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 96)                │           2,400 │ input_layer[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout (Dropout)             │ (None, 96)                │               0 │ dense[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_1 (Dropout)           │ (None, 96)                │               0 │ dropout[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 16)                │           1,552 │ dropout_1[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ classification (Dense)        │ (None, 3)                 │              51 │ dense_2[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ regression (Dense)            │ (None, 1)                 │              17 │ dense_2[0][0]              │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 4,020 (15.70 KB)

 Trainable params: 4,020 (15.70 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
modelf.compile(optimizer=Adam(learning_rate=0.001),loss=["sparse_categorical_crossentropy","mse"],metrics=[["accuracy"],["mae"]])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [45]:
weights= compute_class_weight(class_weight="balanced",classes=np.unique(y_class_train_enc),y=y_class_train_enc)
class_weight_dict = dict(zip(np.unique(y_class_train_enc),weights))

In [46]:
classification_sample_weight = np.array([class_weight_dict[int(value)]
                for value in y_class_train_enc],dtype="float32")

regression_sample_weight = np.ones(len(y_reg_train),dtype="float32")

In [47]:
early_stop = EarlyStopping(monitor="val_loss",patience=5,min_delta=0.0001,restore_best_weights=True)

In [48]:
history = modelf.fit(X_train_p,[y_class_train_enc,y_reg_train],validation_data=(X_test_p,[y_class_test_enc,y_reg_test]),
     sample_weight=[classification_sample_weight,regression_sample_weight],epochs=10,batch_size=256,callbacks=[early_stop],verbose=1)

Epoch 1/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - classification_accuracy: 0.5024 - classification_loss: 0.7646 - loss: 43.1357 - regression_loss: 42.3685 - regression_mae: 3.9414 - val_classification_accuracy: 0.7710 - val_classification_loss: 0.5489 - val_loss: 0.9120 - val_regression_loss: 0.3631 - val_regression_mae: 0.4733
Epoch 2/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.7171 - classification_loss: 0.4567 - loss: 7.6281 - regression_loss: 7.1713 - regression_mae: 2.0371 - val_classification_accuracy: 0.8233 - val_classification_loss: 0.4655 - val_loss: 0.6165 - val_regression_loss: 0.1510 - val_regression_mae: 0.3249
Epoch 3/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.7639 - classification_loss: 0.4156 - loss: 6.0775 - regression_loss: 5.6617 - regression_mae: 1.7909 - val_classification_accuracy: 0.8516 - val_classification_loss: 0.4189 - val_loss: 0.4822 - val_regression_loss: 0.0633 - val_regression_mae: 0.1940
Epoch 4/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.8023 - classification_loss: 0.3799 - loss: 4.5375 - regression_loss: 4.1576 - regression_mae: 1.5044 - val_classification_accuracy: 0.8565 - val_classification_loss: 0.4089 - val_loss: 0.5052 - val_regression_loss: 0.0963 - val_regression_mae: 0.1728
Epoch 5/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.8291 - classification_loss: 0.3443 - loss: 2.9937 - regression_loss: 2.6495 - regression_mae: 1.1588 - val_classification_accuracy: 0.8627 - val_classification_loss: 0.3563 - val_loss: 0.4651 - val_regression_loss: 0.1088 - val_regression_mae: 0.1870
Epoch 6/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - classification_accuracy: 0.8456 - classification_loss: 0.3129 - loss: 2.0086 - regression_loss: 1.6957 - regression_mae: 0.9117 - val_classification_accuracy: 0.8786 - val_classification_loss: 0.3241 - val_loss: 0.4695 - val_regression_loss: 0.1455 - val_regression_mae: 0.3001
Epoch 7/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - classification_accuracy: 0.8554 - classification_loss: 0.3004 - loss: 1.4627 - regression_loss: 1.1623 - regression_mae: 0.7554 - val_classification_accuracy: 0.8734 - val_classification_loss: 0.3416 - val_loss: 0.4374 - val_regression_loss: 0.0958 - val_regression_mae: 0.1791
Epoch 8/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - classification_accuracy: 0.8688 - classification_loss: 0.2891 - loss: 1.1404 - regression_loss: 0.8513 - regression_mae: 0.6422 - val_classification_accuracy: 0.8909 - val_classification_loss: 0.2914 - val_loss: 0.4695 - val_regression_loss: 0.1780 - val_regression_mae: 0.2214
Epoch 9/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.8794 - classification_loss: 0.2794 - loss: 0.9852 - regression_loss: 0.7058 - regression_mae: 0.5860 - val_classification_accuracy: 0.9122 - val_classification_loss: 0.2493 - val_loss: 0.5155 - val_regression_loss: 0.2662 - val_regression_mae: 0.3110
Epoch 10/10
1219/1219 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - classification_accuracy: 0.8920 - classification_loss: 0.2641 - loss: 0.9121 - regression_loss: 0.6479 - regression_mae: 0.5634 - val_classification_accuracy: 0.9220 - val_classification_loss: 0.2270 - val_loss: 0.5776 - val_regression_loss: 0.3505 - val_regression_mae: 0.3376

# Prediction

In [49]:
predictions = modelf.predict(X_test_p)

classification_predictions = (predictions[0])

regression_predictions = (predictions[1])

2438/2438 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step

In [50]:
predicted_class_index = np.argmax(classification_predictions,axis=1)

predicted_class = (label_encoder.inverse_transform(predicted_class_index))
print(predicted_class)
print(regression_predictions)

['at-risk' 'at-risk' 'at-risk' ... 'unhealthy' 'at-risk' 'at-risk']
[[25.25404 ]
 [31.788118]
 [23.723536]
 ...
 [50.459007]
 [24.791233]
 [18.403667]]

# Evaluation

In [51]:
from sklearn.metrics import classification_report

In [52]:
print(classification_report(y_class_test,predicted_class))

              precision    recall  f1-score   support

     at-risk       0.99      0.86      0.92     66951
         fit       0.57      0.95      0.72      4456
   unhealthy       0.50      0.95      0.66      6604

    accuracy                           0.87     78011
   macro avg       0.69      0.92      0.76     78011
weighted avg       0.93      0.87      0.89     78011

In [53]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [54]:
mae = mean_absolute_error(y_reg_test,regression_predictions)

mse = mean_squared_error(y_reg_test,regression_predictions)

rmse = np.sqrt(mse)

r2 = r2_score(y_reg_test,regression_predictions)

In [55]:
print("mean absolute error:",mae)
print("mean squared error:",mse)
print("root mean squared error:",rmse)
print("r2 score:",r2)

mean absolute error: 0.1791481077671051
mean squared error: 0.09585580974817276
root mean squared error: 0.30960589424003665
r2 score: 0.9987992644309998

# Test data

In [56]:
test_data1 = pd.DataFrame({

    "sleep_duration": [8],

    "heart_rate": [68],

    "bmi": [21.5],

    "calorie_expenditure": [600],

    "step_count": [10000],

    "exercise_duration": [60],

    "water_intake": [3.0],

    "diet_type": ["healthy"],

    "stress_level": ["low"],

    "sleep_quality": ["good"],

    "physical_activity_level": ["active"],

    "smoking_alcohol": ["no"],

    "gender": ["female"]

})

test_data1["bmi_risk"] = np.clip(
    (np.maximum(0, 18.5 - test_data1["bmi"]) +
     np.maximum(0, test_data1["bmi"] - 24.9)) / 10, 0, 1
)

test_data1["stress_risk"] = test_data1["stress_level"].map({
    "low": 0, "medium": 0.5, "high": 1
})

test_data1["sleep_duration_risk"] = np.clip(
    abs(test_data1["sleep_duration"] - 8) / 4, 0, 1
)

step_risk = 1 - np.clip(test_data1["step_count"] / 10000, 0, 1)
exercise_risk = 1 - np.clip(test_data1["exercise_duration"] / 60, 0, 1)
calorie_risk = 1 - np.clip(test_data1["calorie_expenditure"] / 600, 0, 1)

test_data1["activity_risk"] = (
    0.4 * step_risk + 0.3 * exercise_risk + 0.3 * calorie_risk
)

hr = test_data1["heart_rate"]
test_data1["heart_rate_risk"] = np.clip(
    np.where(hr < 60, (60 - hr) / 20,
             np.where(hr > 100, (hr - 100) / 40, 0)), 0, 1
)

test_data1["water_risk"] = 1 - np.clip(
    test_data1["water_intake"] / 3, 0, 1
)

test_data1["sleep_quality_risk"] = test_data1["sleep_quality"].map({
    "poor": 1, "average": 0.5, "good": 0
})

test_data1["lifestyle_risk"] = test_data1["smoking_alcohol"].map({
    "no": 0, "occasional": 0.5, "yes": 1
})

In [57]:
# Preprocess test data
test_processed = preprocessing.transform(test_data1)

# Predict
prediction = modelf.predict(test_processed)

# ---------------- Classification Output ----------------
class_probability = prediction[0]

class_index = np.argmax(class_probability, axis=1)

class_name = label_encoder.inverse_transform(class_index)

confidence = np.max(class_probability, axis=1)


# ---------------- Regression Output ----------------
health_risk_score = prediction[1].flatten()[0]


# ---------------- Final Result ----------------
print("Health Condition:", class_name[0])
print("Confidence:", round(confidence[0] * 100, 2), "%")
print("Health Risk Score:", round(health_risk_score, 2))

print("\nClass Probabilities:")

for name, prob in zip(label_encoder.classes_, class_probability[0]):
    print(f"{name}: {prob * 100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
Health Condition: fit
Confidence: 98.06 %
Health Risk Score: 4.12

Class Probabilities:
at-risk: 1.77%
fit: 98.06%
unhealthy: 0.18%

C:\Users\PRAVALLIKA\.conda\envs\mediapipe\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [70]:
test_data1 = pd.DataFrame({

    "sleep_duration": [4.00],

    "heart_rate": [50],

    "bmi": [30.00],

    "calorie_expenditure": [2000],

    "step_count": [5000],

    "exercise_duration": [60],

    "water_intake": [4.20],

    "diet_type": ["veg"],

    "stress_level": ["high"],

    "sleep_quality": ["poor"],

    "physical_activity_level": ["sedentary"],

    "smoking_alcohol": ["yes"],

    "gender": ["female"]

})

test_data1["bmi_risk"] = np.clip(
    (np.maximum(0, 18.5 - test_data1["bmi"]) +
     np.maximum(0, test_data1["bmi"] - 24.9)) / 10, 0, 1
)

test_data1["stress_risk"] = test_data1["stress_level"].map({
    "low": 0, "medium": 0.5, "high": 1
})

test_data1["sleep_duration_risk"] = np.clip(
    abs(test_data1["sleep_duration"] - 8) / 4, 0, 1
)

step_risk = 1 - np.clip(test_data1["step_count"] / 10000, 0, 1)
exercise_risk = 1 - np.clip(test_data1["exercise_duration"] / 60, 0, 1)
calorie_risk = 1 - np.clip(test_data1["calorie_expenditure"] / 600, 0, 1)

test_data1["activity_risk"] = (
    0.4 * step_risk + 0.3 * exercise_risk + 0.3 * calorie_risk
)

hr = test_data1["heart_rate"]
test_data1["heart_rate_risk"] = np.clip(
    np.where(hr < 60, (60 - hr) / 20,
             np.where(hr > 100, (hr - 100) / 40, 0)), 0, 1
)

test_data1["water_risk"] = 1 - np.clip(
    test_data1["water_intake"] / 3, 0, 1
)

test_data1["sleep_quality_risk"] = test_data1["sleep_quality"].map({
    "poor": 1, "average": 0.5, "good": 0
})

test_data1["lifestyle_risk"] = test_data1["smoking_alcohol"].map({
    "no": 0, "occasional": 0.5, "yes": 1
})

In [71]:
# Preprocess test data
test_processed = preprocessing.transform(test_data1)

# Predict
prediction = modelf.predict(test_processed)

# ---------------- Classification Output ----------------
class_probability = prediction[0]

class_index = np.argmax(class_probability, axis=1)

class_name = label_encoder.inverse_transform(class_index)

confidence = np.max(class_probability, axis=1)


# ---------------- Regression Output ----------------
health_risk_score = prediction[1].flatten()[0]


# ---------------- Final Result ----------------
print("Health Condition:", class_name[0])
print("Confidence:", round(confidence[0] * 100, 2), "%")
print("Health Risk Score:", round(health_risk_score, 2))

print("\nClass Probabilities:")

for name, prob in zip(label_encoder.classes_, class_probability[0]):
    print(f"{name}: {prob * 100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
Health Condition: unhealthy
Confidence: 99.98 %
Health Risk Score: 58.54

Class Probabilities:
at-risk: 0.01%
fit: 0.00%
unhealthy: 99.98%

In [60]:
import pickle 
with open(r"C:\Users\PRAVALLIKA\OneDrive\New folder\annf.pkl","wb") as f:
    pickle.dump(preprocessing,f)

In [61]:
modelf.save(r"C:\Users\PRAVALLIKA\OneDrive\New folder\ANNf.keras")

In [62]:
from keras.models import load_model
deployment=load_model(r"C:\Users\PRAVALLIKA\OneDrive\New folder\ANNf.keras")

In [63]:
prediction = deployment.predict(
    test_processed,
    verbose=0
)

print("Prediction type:", type(prediction))

print("Number of outputs:", len(prediction))

print("Classification output:", prediction[0])

print("Regression output:", prediction[1])

Prediction type: <class 'list'>
Number of outputs: 2
Classification output: [[2.5091824e-04 1.6990896e-05 9.9973208e-01]]
Regression output: [[54.613056]]